config: conf/train_asr_tedlium_conformer_l1024.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/asr_d8_l1024_multilayer_hubert
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 8
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 39451
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: true
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 50
patience: null
val_scheduler_criterion:
- valid
- acc
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
nbest_averaging_interval: 0
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: 5000
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: true
wandb_project: tedsummary
wandb_id: null
wandb_entity: null
wandb_name: conformer_ted3_sub8_l1024
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param:
- frontend.upstream
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 600000
valid_batch_bins: null
train_shape_file:
- exp/asr_stats_tedlium3/train/speech_shape
- exp/asr_stats_tedlium3/train/text_shape.bpe
valid_shape_file:
- exp/asr_stats_tedlium3/valid/speech_shape
- exp/asr_stats_tedlium3/valid/text_shape.bpe
batch_type: length
valid_batch_type: null
fold_length:
- 800
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/extracted/train_sp/feats.scp
    - speech
    - kaldi_ark
-   - dump/extracted/train_sp/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/extracted/dev/feats.scp
    - speech
    - kaldi_ark
-   - dump/extracted/dev/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000
token_list:
- <blank>
- <unk>
- '[SEP]'
- ▁
- s
- e
- t
- ','
- ▁the
- a
- .
- d
- ▁a
- n
- ing
- y
- o
- ▁and
- ▁to
- ▁of
- p
- g
- ar
- u
- i
- m
- ed
- ▁in
- re
- er
- or
- al
- r
- l
- c
- x
- in
- ▁f
- b
- ▁c
- f
- k
- ;
- '&#'
- 27;
- 'on'
- le
- quot
- an
- th
- h
- en
- ic
- v
- '-'
- it
- es
- ri
- ▁--
- w
- ▁A
- ly
- ▁b
- ▁S
- ur
- ▁for
- ▁that
- ▁we
- ve
- ▁be
- at
- ma
- ch
- ter
- ▁re
- ro
- ra
- '?'
- ▁by
- ▁w
- st
- ▁C
- se
- ▁de
- la
- ent
- el
- ▁is
- ▁M
- il
- ▁how
- ▁it
- ▁on
- ▁p
- ▁&
- ect
- ▁with
- im
- ation
- ▁In
- ▁you
- te
- lo
- ion
- li
- ▁can
- ▁B
- ce
- un
- am
- ▁The
- ▁st
- ol
- ac
- ne
- ▁us
- ▁an
- ▁this
- vi
- ▁di
- ▁do
- ha
- ▁he
- ▁from
- ad
- ity
- ul
- ate
- ▁P
- ir
- hi
- ▁talk
- ▁W
- us
- and
- et
- ive
- ist
- ▁D
- ies
- z
- ▁T
- tion
- he
- ▁con
- ver
- ▁our
- ▁about
- ▁world
- ▁G
- ho
- ck
- ers
- ▁E
- is
- as
- ▁co
- ':'
- ▁me
- ca
- ig
- po
- ▁mo
- id
- op
- ▁pro
- ment
- ▁her
- ▁are
- ll
- ▁your
- ▁How
- ▁his
- ▁she
- ut
- om
- ta
- ▁I
- ill
- ight
- qu
- ▁says
- '0'
- ke
- '1'
- age
- j
- ▁N
- ▁so
- ▁F
- ▁share
- mi
- '&'
- tra
- ▁un
- ▁H
- ci
- ▁what
- ▁work
- ▁more
- if
- iv
- com
- der
- ound
- ▁pa
- ▁as
- ical
- ▁new
- ▁make
- ting
- ▁people
- ▁their
- ant
- ff
- ide
- ▁sp
- R
- me
- ng
- ▁life
- mo
- em
- ine
- end
- )
- man
- ▁(
- ▁all
- ▁have
- bo
- ▁comp
- J
- ▁help
- ▁TED
- ▁human
- ▁out
- ▁K
- ful
- ▁way
- co
- pe
- ud
- ph
- ▁ex
- ▁at
- ture
- est
- tic
- ▁some
- har
- '&#39;'
- ia
- king
- ',&'
- ▁into
- ▁What
- form
- ▁power
- able
- ance
- ▁was
- ence
- um
- ▁they
- ▁but
- ry
- I
- ▁up
- ▁like
- ▁who
- gen
- ▁change
- wa
- ▁O
- ood
- ▁not
- ▁pre
- ▁could
- cial
- ous
- ▁per
- ow
- ell
- one
- ▁narrat
- ▁one
- ▁He
- ▁has
- ▁need
- day
- ▁music
- mb
- ther
- ▁go
- ru
- ▁plan
- ▁exp
- ▁every
- ize
- Direct
- '].'
- ▁no
- old
- L
- ative
- cu
- ▁future
- A
- ▁real
- tru
- ▁live
- ▁time
- ▁shows
- ian
- V
- ▁get
- ▁than
- ish
- ▁know
- ▁Le
- ▁when
- ▁take
- ▁dr
- ▁why
- ▁art
- '2'
- ious
- ▁act
- ▁other
- ▁just
- .&
- ▁But
- ▁most
- ▁see
- port
- ▁build
- less
- T
- U
- '3'
- ang
- ▁20
- ▁design
- ▁over
- ▁Why
- ▁create
- ▁story
- ▁think
- ▁climate
- low
- ▁trans
- ▁Jo
- ▁learn
- ▁health
- ▁through
- ▁Ro
- ▁even
- ▁will
- ▁years
- ▁global
- ▁look
- ▁where
- rge
- ▁ga
- ▁part
- long
- cent
- '5'
- ▁lead
- W
- ible
- ▁system
- ▁call
- '9'
- ▁technolog
- line
- ▁La
- ▁own
- ▁explains
- ▁brain
- ▁data
- This
- ▁Anderson
- ▁tell
- ▁And
- ▁start
- Y
- ▁Re
- ▁better
- ough
- S
- ▁idea
- O
- ▁explore
- ▁which
- ▁find
- ▁research
- ▁women
- ▁problem
- ▁grow
- ologist
- ▁right
- ▁history
- ▁Li
- ▁science
- ▁first
- ▁develop
- D
- ▁two
- ▁...
- '4'
- ▁Addis
- ▁Africa
- ▁should
- ▁US
- ▁three
- ▁Fellow
- ▁space
- ▁understand
- C
- ▁back
- ▁child
- ▁stories
- ▁personal
- ▁question
- E
- P
- ▁between
- ▁happen
- M
- ▁You
- ▁experience
- ▁home
- '8'
- ▁scientist
- ▁play
- Z
- ▁America
- ▁With
- ▁down
- ▁produc
- ▁surprising
- cross
- ▁place
- ▁turn
- '7'
- ▁reveal
- ▁would
- ▁high
- ▁million
- ▁next
- '6'
- ▁much
- ▁great
- ▁challenge
- ▁teach
- ▁Studio
- ▁conversation
- ▁without
- source
- ization
- ▁energy
- N
- ▁each
- B
- ▁show
- ▁vision
- ▁disease
- ability
- ▁break
- ▁Chris
- G
- ▁business
- ▁solution
- ▁behind
- K
- '!'
- H
- F
- Q
- /
- X
- '%'
- q
- '@'
- ''''
- ']'
- +
- '|'
- _
- '"'
- (
- $
- '['
- '*'
- '='
- '#'
- '`'
- <sos/eos>
init: xavier_uniform
input_size: 1024
ctc_conf:
    ignore_nan_grad: true
joint_net_conf: null
use_preprocessor: true
token_type: bpe
bpemodel: data/en_token_list/bpe_unigram500/bpe.model
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
short_noise_thres: 0.5
frontend: null
frontend_conf: {}
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
normalize: null
normalize_conf: {}
model: espnet
model_conf:
    ctc_weight: 0.4
    lsm_weight: 0.15
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
preencoder: linear
preencoder_conf:
    input_size: 1024
    output_size: 80
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d8
    normalize_before: false
    macaron_style: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31
postencoder: null
postencoder_conf: {}
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 512
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
preprocessor: default
preprocessor_conf: {}
required:
- output_dir
- token_list
version: '202209'
distributed: true
